config/routes.rb
Rails.application.routes.draw do
  root controller: :visitors, action: :index
  devise_for :users

  namespace :cabinet do
    root controller: :dashboard, action: :dashboard
    resources :users
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default("")
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#

class User < ApplicationRecord
  has_one :profile, inverse_of: :user, dependent: :destroy
  accepts_nested_attributes_for :profile, allow_destroy: true
  validates_presence_of :profile
  Profile::TYPES.each do |_, value|
    delegate "#{value}?", to: :profile
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :invitable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def profile_type
    Profile.human_attribute_name("profile_type/#{profile.type}")
  end
end

app/controllers/cabinet/base_controller.rb
module Cabinet
  class BaseController < ApplicationController
    layout 'cabinet'
  end
end

app/controllers/cabinet/dashboard_controller.rb
module Cabinet
  class DashboardController < BaseController
    def dashboard
      authorize current_user
    end
  end
end

app/controllers/cabinet/users_controller.rb
module Cabinet
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit update destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show; end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit; end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/helpers/cabinet/dashboard_helper.rb
module Cabinet
  module DashboardHelper
  end
end

app/helpers/cabinet/menu_helper.rb
module Cabinet
  module MenuHelper
    ##
    # Create a sidebar menu element in cabinet.
    #
    # @param [Hash] options The options hash.
    # @option options [Class] :model Resource for menu link.
    # @option options [String] :action Action for menu link.
    # @option options [String] :name Menu link text
    # @option options [String] :url Link href.
    # @option options [String] :icon (false) Link icon css class.
    # @option options [String] :level (false) Level of menu nesting.
    # @param [Block] &block Nested menu block.
    def sidebar_item(options = {})
      model = options[:model] || :application
      action, name, url, icon, level = options.values_at(:action, :name, :url, :icon, :level)
      return unless policy(model).send "#{action}?"

      icon_html = icon.present? ? content_tag(:i, nil, class: %W[fa #{icon} fa-fw]) : ''

      if block_given?
        nav_level = %w[second third][level.to_i]
        arrow_html = content_tag(:span, nil, class: %w[fa arrow]).html_safe
        subitem_html = content_tag :ul, nil, class: %W[nav nav-#{nav_level}-level collapse] do
          yield(level.to_i + 1).html_safe
        end
      end

      link_html = link_to "#{icon_html}#{name}#{level}#{arrow_html}".html_safe,
                          url,
                          class: (current_page?(url) ? :active : nil)

      content_tag :li, "#{link_html.html_safe}#{subitem_html}".html_safe
    end
  end
end

app/views/cabinet/users/_form.html.slim
= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @user.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@user.errors.count,"error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :email, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :email, class: "form-control"
  .form-group
    = f.label :password, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :password, class: "form-control"
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/cabinet/users/edit.html.slim
.page-header
  = link_to users_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @user, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | user

= render 'form'

app/views/cabinet/users/index.html.slim
.page-header
  = link_to new_user_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Tser
  h1
    | Listing users

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Email
        th
          | Password
        th
          | Name
        th
        th
        th
    tbody
      - @users.each do | user |
        tr
          td
            = user.email
          td
            = user.password
          td
            = user.name
          td
            = link_to 'Show', user
          td
            = link_to 'Edit', edit_user_path(user) 
          td
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/cabinet/users/new.html.slim
.page-header
  = link_to users_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | user

= render 'form'

app/views/cabinet/users/show.html.slim
.page-header
  = link_to users_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_user_path(@user), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show user
dl.dl-horizontal
  dt
    | Email:
  dd
    = @user.email
  dt
    | Password:
  dd
    = @user.password
  dt
    | Name:
  dd
    = @user.name