config/routes.rb
Rails.application.routes.draw do
  root controller: :visitors, action: :index
  devise_for :users

  namespace :cabinet do
    root controller: :dashboard, action: :dashboard
    resources :users
  end
end

app/controllers/cabinet/base_controller.rb
module Cabinet
  class BaseController < ApplicationController
    layout 'cabinet'
  end
end

app/controllers/cabinet/dashboard_controller.rb
module Cabinet
  class DashboardController < BaseController
    def dashboard
      authorize current_user
    end
  end
end

app/controllers/cabinet/users_controller.rb
module Cabinet
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit update destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show; end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit; end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :name)
    end
  end
end

app/helpers/cabinet/dashboard_helper.rb
module Cabinet
  module DashboardHelper
  end
end

app/helpers/cabinet/menu_helper.rb
module Cabinet
  module MenuHelper
    ##
    # Create a sidebar menu element in cabinet.
    #
    # @param [Hash] options The options hash.
    # @option options [Class] :model Resource for menu link.
    # @option options [String] :action Action for menu link.
    # @option options [String] :name Menu link text
    # @option options [String] :url Link href.
    # @option options [String] :icon (false) Link icon css class.
    # @option options [String] :level (false) Level of menu nesting.
    # @param [Block] &block Nested menu block.
    def sidebar_item(options = {})
      model = options[:model] || :application
      action, name, url, icon, level = options.values_at(:action, :name, :url, :icon, :level)
      return unless policy(model).send "#{action}?"

      icon_html = icon.present? ? content_tag(:i, nil, class: %W[fa #{icon} fa-fw]) : ''

      if block_given?
        nav_level = %w[second third][level.to_i]
        arrow_html = content_tag(:span, nil, class: %w[fa arrow]).html_safe
        subitem_html = content_tag :ul, nil, class: %W[nav nav-#{nav_level}-level collapse] do
          yield(level.to_i + 1).html_safe
        end
      end

      link_html = link_to "#{icon_html}#{name}#{level}#{arrow_html}".html_safe,
                          url,
                          class: (current_page?(url) ? :active : nil)

      content_tag :li, "#{link_html.html_safe}#{subitem_html}".html_safe
    end
  end
end

app/views/cabinet/base/_page_title.html.slim
- if content_for?(:page_title)
  .row
    .col-lg-12
      h1.page-header
        == yield(:page_title)

app/views/cabinet/base/_quick_search.html.slim
li.sidebar-search
  .input-group.custom-search-form
    input.form-control placeholder="Search..." type="text" /
    span.input-group-btn
      button.btn.btn-default type="button"
        i.fa.fa-search

app/views/cabinet/base/_sidebar.html.slim
/! /input-group
= sidebar_item model: :application, action: :dashboard, url: cabinet_root_path, name: 'Dashboard', icon: 'fa-dashboard'
= sidebar_item model: :user, action: :index, url: cabinet_users_path, name: 'Users', icon: 'fa-users' do |level|
  = sidebar_item model: :user, action: :new, url: new_cabinet_user_path, name: 'Add user', icon: 'fa-user-plus', level: level do
    = sidebar_item model: :user, action: :new, url: new_user_invitation_path, name: 'Remove user', icon: 'fa-user-times'
/!
  li
    a href="#{cabinet_root_path}"
      i.fa.fa-dashboard.fa-fw
      | Old Dashboard
  li
    a.active href="#"
      i.fa.fa-bar-chart-o.fa-fw
      | Charts
      span.fa.arrow
    ul.nav.nav-second-level.collapse
      li
        a href="flot.html"  Flot Charts
      li
        a href="morris.html"  Morris.js Charts
  /! /.nav-second-level
  li
    a href="tables.html"
      i.fa.fa-table.fa-fw
      | Tables
  li
    a href="forms.html"
      i.fa.fa-edit.fa-fw
      | Forms
  li
    a.active href="#"
      i.fa.fa-wrench.fa-fw
      | UI Elements
      span.fa.arrow
    ul.nav.nav-second-level.collapse
      li
        a href="panels-wells.html"  Panels and Wells
      li
        a href="buttons.html"  Buttons
      li
        a href="notifications.html"  Notifications
      li
        a href="typography.html"  Typography
      li
        a href="icons.html"  Icons
      li
        a href="grid.html"  Grid
  /! /.nav-second-level
  li
    a.active href="#"
      i.fa.fa-sitemap.fa-fw
      | Multi-Level Dropdown
      span.fa.arrow
    ul.nav.nav-second-level.collapse.in
      li
        a.active href="#"  Second Level Item
      li
        a.active href="#"  Second Level Item
      li
        a.active href="#"
          | Third Level
          span.fa.arrow
        ul.nav.nav-third-level.collapse.in
          li
            a.active href="#"  Third Level Item
          li
            a.active href="#"  Third Level Item
          li
            a.active href="#"  Third Level Item
          li
            a.active href="#"  Third Level Item
  /! /.nav-third-level
  /! /.nav-second-level
  li
    a.active href="#"
      i.fa.fa-files-o.fa-fw
      | Sample Pages
      span.fa.arrow
    ul.nav.nav-second-level.collapse
      li
        a href="blank.html"  Blank Page
      li
        a href="login.html"  Login Page
  /! /.nav-second-level
  /! /.sidebar-collapse